# Generated by Django 5.1.4 on 2025-05-22 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_zarinpal_data_order_zarinpal_ref_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='zarinpal_authority',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zarinpal_data',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zarinpal_ref_id',
        ),
    ]
