services:
    redis:
      image: redis
      container_name: redis
      ports:
        - "6379:6379"

    celery:
      image: python:3.12
      container_name: celery_worker
      depends_on: 
        - redis
      volumes:
        - .:/app
      working_dir: /app
      environment:
        - CELERY_BROKER_URL=redis://redis:6379/1
      command: sh -c "pip install celery && celery -A config worker --loglevel=info"

